export {default as Login} from './login'
export {default as Register} from './Register'
export {default as Home} from './home'
export {default as SplashScreen} from './splash-screen'
export {default as Record} from './record'
export {default as Profile} from './profile'